# Generated by Django 4.1 on 2023-06-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Backup',
        ),
    ]
