# Generated by Django 4.1 on 2023-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_backup_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=215, verbose_name='name of the scanResult')),
                ('date_added', models.DateTimeField(verbose_name='date and time when a scanResult was added to the database')),
                ('path', models.CharField(max_length=1000, verbose_name='scanResult directory file system path')),
            ],
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
