# Generated by Django 4.1 on 2023-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_scanresult_delete_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='operating_system',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('unknown', 'Unknown OS')], default='unknown', max_length=215, verbose_name='device OS'),
        ),
    ]
