# Generated by Django 4.1 on 2023-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_scanresult_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='mvt_version',
            field=models.CharField(default='N/A', max_length=215, verbose_name='version of MVT used for the scan'),
        ),
    ]
