# Generated by Django 4.1 on 2023-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_scanresult_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='warnings',
            field=models.CharField(default='', max_length=100, verbose_name='warings resulted from the MVT scan'),
        ),
    ]
