# Generated by Django 4.1 on 2023-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_scanresult_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='warnings',
            field=models.CharField(default='', max_length=10000, verbose_name='warings resulted from the MVT scan'),
        ),
    ]
